package org.eclipse.swt.events;

import org.eclipse.swt.widgets.Control;
import org.eclipse.swt.widgets.Shell;

/**
 * Classes which implement this interface provide methods that deal with the
 * vents that are generated by moving and resizing controls.
 * <p>
 * After creating an instance of a class that implements this interface it can
 * be added to a control using the
 * {@link Control#addControlListener(ControlListener)} method and removed using
 * the {@link Control#removeControlListener(ControlListener)} method. When a
 * control is moved or resized, the appropriate method will be invoked.
 */
public interface ControlListener extends TypedListener {
  /**
   * Sent when the location (x, y) of a control changes relative to its paren
   * (or relative to the display, for {@link Shell}s).
   *
   * @param e an event containing information about the move
   */
  void controlMoved(ControlEvent e);

  /**
   * Sent when the size (width, height) of a control changes.
   *
   * @param e an event containing information about the resize
   */
  void controlResized(ControlEvent e);
}
